# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sanchez Lozano Jonathan
title: Tecnologo profesional en informatica
email: jonathan.sanchez7681@alumnos.udg.mx
website: www.github.com/JonathanSanchez09/JonathanSanchez09.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: facespics
github_username: JonathanSanchez09
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: Byjonny09
linkedin_username: sanchez-lozano-jonathan-336726265
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: jonathansanchezlozano2386
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Saludos, Me llamo jonathan y soy tecnologo profesional en informatica. Actualmente estoy cursando la universidad estudiando la carrera de ingeneria en computacion. Ademas tuve la oportunidad de hacer mis practicas en una empresa donde pude aplicar mis conocimientos basicos de redes de computo ademas, opere y di mantenimiento a equipos de cómputo. He trabajado en varios trabajos adquiriendo experiencia en atencion al cliente, trabajo en equipo, liderazgo y siendo autodidacta. 

  Mis mayores habilidades son en: <mark>Capacitación de usuarios en informática </mark> and <mark>Diseña Programas y Páginas Web </mark>

content:
  - title: Proyectos # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Los mejores proyectos que veras
        link: github.com/JonathanSanchez09
        # link_text: Project Website
        additional_links:
          - title:  JonathanSanchez09/JonathanSanchez09.github.io
            icon: fab fa-github
            url: github.com/JonathanSanchez09/JonathanSanchez09.github.io
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Ser un programador promedio no es parte de mi estilo de vida, checa estos maravillosos proyectos
        description: | # this will include new lines to allow paragraphs
          Empece a programar por gusto personal desde que tengo 15 años y desde entonces cada dia me esfuerzo mas para demostrarle al mundo de lo que puedo lograr. He desarrollado muchas habilidades a traves de mis estudios y estoy muy orgulloso de lo que tengo y de lo quedo ser capaz de desarrollar. Si puedes imaginarlo yo puedo programarlo.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Educación # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Centro Universitario de Ciencias Exactas e Ingenierías
        caption: 2020 - 2023
        sub_title: Ingeniería en computación
        quote: >
          El Centro Universitario de Ciencias Exactas e Ingenierías es la división de la Universidad de Guadalajara en Jalisco, México, destinada a la educación superior relacionada con los campos de ingenierías, ciencias físicas, químicas y matemáticas
        description: | # this will include new lines to allow paragraphs
          Durante mi tiempo en CUCEI, desarrolle mis habilidades mas importantes a lo largo de los años tomando l asignaturas de mi carrera, como programacion en diferentes lenguajes como c, c++, python y java. Tambien operar redes, tanto la instalacion y su respectiva configuración y el diseño de paginas web en html con css. Fue muy satisfactorio mi estancia en la universidad ademas apredi mucho trabajar en equipo, ser un buen lider de grupo, y siempre cumplir mis objetivos en un tiempo definido.

  - title: Un poco mas sobre mi
    layout: text
    content: | # this will include new lines to allow paragraphs
      Además de mi interes acerca de redes e desarrollo de videojuegos, algunos de mis hábitos atómicos son:
      - Leer
      - Ejercicio
      - Jugar Videojuegos
      - Ver partidos de futbol

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
